### ISSUE TITLE
DATA URI scheme is not usable

### ISSUE THREAD

**Issue by nsonaniya2010** [Nhoya/PastebinMarkdownXSS#3]
In later version of firefox and other browser data uri scheme doesn't fetch previous domain i.e. you can only popup your own input but can not popup domain and hence not document.cookie :)

**Comment by Nhoya** [comment]
Thanks for the additional clarification  :+1: . What about the second payload ? 

By the way it works with older browser versions, this doesn't mean that is not usable, just not vs newer browsers

**Comment by nsonaniya2010** [comment]
I didn't worked with second one but instead of trying to fire your own input you should try to fire either docuemnt.domain or cookie :)
